<a href="https://colab.research.google.com/github/naveenprasad07/pytorch/blob/main/00_pytorch_fudamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [70]:
import torch
import numpy

In [71]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


### Introduction to Tensors

#### Creating Tensors

In [72]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [73]:
scalar.ndim

0

In [74]:
# Get tensor back as Python int
scalar.item()

7

In [75]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [76]:
vector.ndim

1

In [77]:
vector.shape

torch.Size([2])

In [78]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [79]:
MATRIX.ndim

2

In [80]:
MATRIX[0]

tensor([7, 8])

In [81]:
MATRIX[1]

tensor([ 9, 10])

In [82]:
MATRIX.shape

torch.Size([2, 2])

In [83]:
# TENSOR
TENSOR =  torch.tensor([[[1,2,3],[3,6,9],[2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [84]:
TENSOR.ndim

3

In [85]:
TENSOR.shape

torch.Size([1, 3, 3])

In [86]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

### Random Tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

``` Start with random nubmers -> look at data -> update random numbers -> look at data -> update random nubmers```


In [87]:
# Create a random tensor of size (3,4 )
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2055, 0.6272, 0.4506, 0.9765],
        [0.8726, 0.9836, 0.3338, 0.7684],
        [0.3902, 0.0422, 0.0329, 0.0113]])

In [88]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [89]:
random_tensor.ndim

2

In [90]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3,224,224)) # height,width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [91]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [92]:
ones = torch.ones ( size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [93]:
ones.dtype

torch.float32

In [94]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [95]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start = 0,end = 1000, step = 1)
one_to_ten

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 1

In [96]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [97]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None # what datatype is the tensor?
                               ,device = None, # What device is your tensor on
                               requires_grad=False # Whether or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [98]:
float_32_tensor.dtype

torch.float32

In [99]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [100]:
float_16_tensor.dtype

torch.float16

In [101]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [102]:
int_64_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_64_tensor

tensor([3, 6, 9])

In [103]:
float_32_tensor * int_64_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [104]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5206, 0.7770, 0.0781, 0.9928],
        [0.9490, 0.4432, 0.7714, 0.8223],
        [0.1001, 0.9031, 0.3125, 0.8719]])

In [105]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [106]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.5206, 0.7770, 0.0781, 0.9928],
        [0.9490, 0.4432, 0.7714, 0.8223],
        [0.1001, 0.9031, 0.3125, 0.8719]])
Datatype of tensor: torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


### Manipulating Tensors (tensor operations)

Tensor operatins include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [107]:
### Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [108]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [109]:
# Subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [110]:
# Try out PyTorch in-builtin functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [111]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the outer dimensions:
* `` (2, 3) * (3, 2) -> (2, 2) ``
* `` (3, 2) * (2, 3) -> (3, 3) ``


In [112]:
torch.matmul(torch.rand(10,10),torch.rand(10,10)).shape

torch.Size([10, 10])

In [113]:
# Element wise multiplication
print(tensor, "*",tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [114]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [115]:
tensor @ tensor

tensor(14)

In [116]:
# Matrix multiplication
1 * 1 + 2 * 2  + 3 * 3

14

In [117]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.88 ms, sys: 0 ns, total: 1.88 ms
Wall time: 1.61 ms


In [118]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 284 µs, sys: 0 ns, total: 284 µs
Wall time: 219 µs


tensor(14)

##### One of the most common errors in deep learning : shape errors

In [121]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],[3,4],[5,6]])

tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

torch.matmul(tensor_A,tensor_B) # torch.mm is the same as torch.matmul (it's an alias for matmul)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [122]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix out tensor shape issues, we can manipulate the spae of one of our tensor using a **transpose**

A transpose switches the axes or dimensions of a given tensor

In [123]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [124]:
tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [125]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [126]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes : tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.shape} <- inner dimensions must match")
print("Output : \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\n Output shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes : tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) <- inner dimensions must match
Output : 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

 Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [127]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [128]:
# Find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [130]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [133]:
# Find the mean - note : the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [134]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [135]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [136]:
# Find the position in tensor that has the minimum value with argmin() -> return index position of target tensor  where the minimum value occurs
x.argmin()

tensor(0)

In [137]:
x[0]

tensor(0)

In [138]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [140]:
x[9]

tensor(90)

In [141]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each oher (v stack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [151]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [152]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [153]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [154]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [158]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [164]:
# torch.squee() - removes all singled dimensions from a target tensor
print( f" Previous tensor : {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimesions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor : {x_squeezed}")
print(f"New shape : {x_squeezed.shape}")

 Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape : torch.Size([9])


In [165]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target : {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\n New tensor: {x_unsqueezed}")
print(f"New shape :{x_unsqueezed.shape}")

Previous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

 New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape :torch.Size([1, 9])


In [168]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1 , 1 -> 2 , 2-> 0

print(f"Previous shape : {x_original.shape}")
print(f"New shape : {x_permuted.shape}")

Previous shape : torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


In [169]:
x_original

tensor([[[0.9507, 0.4105, 0.1224],
         [0.9820, 0.3109, 0.3044],
         [0.9089, 0.8676, 0.7760],
         ...,
         [0.9084, 0.3735, 0.9317],
         [0.7757, 0.7666, 0.5947],
         [0.9190, 0.4610, 0.4274]],

        [[0.0391, 0.2132, 0.3167],
         [0.0673, 0.4074, 0.7075],
         [0.3970, 0.0590, 0.9854],
         ...,
         [0.8931, 0.6843, 0.9718],
         [0.0295, 0.2193, 0.0875],
         [0.5130, 0.8338, 0.5744]],

        [[0.4258, 0.3883, 0.4535],
         [0.8586, 0.3717, 0.3021],
         [0.2327, 0.3513, 0.6277],
         ...,
         [0.0087, 0.5843, 0.0853],
         [0.1919, 0.5645, 0.0231],
         [0.9136, 0.8620, 0.4315]],

        ...,

        [[0.8031, 0.1917, 0.3507],
         [0.9392, 0.4666, 0.4597],
         [0.1163, 0.9586, 0.5059],
         ...,
         [0.6616, 0.3887, 0.5643],
         [0.5127, 0.3402, 0.3072],
         [0.3683, 0.5497, 0.2274]],

        [[0.9199, 0.0053, 0.4091],
         [0.9607, 0.6703, 0.1169],
         [0.

In [170]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [172]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [173]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [174]:
# Let's index on the middle bracket (dim=1)

x[0][0]

tensor([1, 2, 3])

In [176]:
# Let's index on the most inner bracket
x[0][1][1]

tensor(5)

In [177]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [178]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [179]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1,1]

tensor([5])

In [180]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])