<a href="https://colab.research.google.com/github/naveenprasad07/pytorch/blob/main/00_pytorch_fudamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy

In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


### Introduction to Tensors

#### Creating Tensors

In [8]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [10]:
# Get tensor back as Python int
scalar.item()

7

In [12]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX[0]

tensor([7, 8])

In [18]:
MATRIX[1]

tensor([ 9, 10])

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
# TENSOR
TENSOR =  torch.tensor([[[1,2,3],[3,6,9],[2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

### Random Tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

``` Start with random nubmers -> look at data -> update random numbers -> look at data -> update random nubmers```


In [29]:
# Create a random tensor of size (3,4 )
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0157, 0.9974, 0.7422, 0.8870],
        [0.5427, 0.6828, 0.1411, 0.0834],
        [0.1791, 0.1890, 0.4193, 0.0201]])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [26]:
random_tensor.ndim

2

In [34]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3,224,224)) # height,width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [38]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
ones = torch.ones ( size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
ones.dtype

torch.float32

In [41]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [43]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start = 0,end = 1000, step = 1)
one_to_ten

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 1

In [45]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [51]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None # what datatype is the tensor?
                               ,device = None, # What device is your tensor on
                               requires_grad=False # Whether or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [52]:
float_32_tensor.dtype

torch.float32

In [55]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [58]:
float_16_tensor.dtype

torch.float16

In [59]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [64]:
int_64_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_64_tensor

tensor([3, 6, 9])

In [65]:
float_32_tensor * int_64_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [66]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7111, 0.2551, 0.4319, 0.4029],
        [0.7857, 0.7090, 0.6603, 0.6036],
        [0.6962, 0.7615, 0.7059, 0.6649]])

In [68]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [70]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.7111, 0.2551, 0.4319, 0.4029],
        [0.7857, 0.7090, 0.6603, 0.6036],
        [0.6962, 0.7615, 0.7059, 0.6649]])
Datatype of tensor: torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


### Manipulating Tensors (tensor operations)

Tensor operatins include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [74]:
### Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [73]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [75]:
# Subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [76]:
# Try out PyTorch in-builtin functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [77]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the outer dimensions:
* `` (2, 3) * (3, 2) -> (2, 2) ``
* `` (3, 2) * (2, 3) -> (3, 3) ``


In [87]:
torch.matmul(torch.rand(10,10),torch.rand(10,10)).shape

torch.Size([10, 10])

In [78]:
# Element wise multiplication
print(tensor, "*",tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [79]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [84]:
tensor @ tensor

tensor(14)

In [80]:
# Matrix multiplication
1 * 1 + 2 * 2  + 3 * 3

14

In [82]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.54 ms, sys: 0 ns, total: 1.54 ms
Wall time: 3.99 ms


In [83]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 930 µs, sys: 7 µs, total: 937 µs
Wall time: 797 µs


tensor(14)

##### One of the most common errors in deep learning : shape errors

In [92]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],[3,4],[5,6]])

tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

torch.matmul(tensor_A,tensor_B) # torch.mm is the same as torch.matmul (it's an alias for matmul)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [91]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix out tensor shape issues, we can manipulate the spae of one of our tensor using a **transpose**

A transpose switches the axes or dimensions of a given tensor

In [93]:
tensor_B

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [96]:
tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [97]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [102]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes : tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.shape} <- inner dimensions must match")
print("Output : \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\n Output shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes : tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) <- inner dimensions must match
Output : 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

 Output shape: torch.Size([3, 3])
