<a href="https://colab.research.google.com/github/naveenprasad07/pytorch/blob/main/00_pytorch_fudamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
import torch
import numpy

In [67]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


### Introduction to Tensors

#### Creating Tensors

In [68]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [69]:
scalar.ndim

0

In [70]:
# Get tensor back as Python int
scalar.item()

7

In [71]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [72]:
vector.ndim

1

In [73]:
vector.shape

torch.Size([2])

In [74]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [75]:
MATRIX.ndim

2

In [76]:
MATRIX[0]

tensor([7, 8])

In [77]:
MATRIX[1]

tensor([ 9, 10])

In [78]:
MATRIX.shape

torch.Size([2, 2])

In [79]:
# TENSOR
TENSOR =  torch.tensor([[[1,2,3],[3,6,9],[2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [80]:
TENSOR.ndim

3

In [81]:
TENSOR.shape

torch.Size([1, 3, 3])

In [82]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

### Random Tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

``` Start with random nubmers -> look at data -> update random numbers -> look at data -> update random nubmers```


In [83]:
# Create a random tensor of size (3,4 )
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9784, 0.5085, 0.5301, 0.0052],
        [0.2319, 0.5885, 0.5584, 0.0195],
        [0.3456, 0.6826, 0.5070, 0.9702]])

In [84]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [85]:
random_tensor.ndim

2

In [86]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3,224,224)) # height,width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [87]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [88]:
ones = torch.ones ( size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [89]:
ones.dtype

torch.float32

In [90]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [91]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start = 0,end = 1000, step = 1)
one_to_ten

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 1

In [92]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch & deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [93]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype = None # what datatype is the tensor?
                               ,device = None, # What device is your tensor on
                               requires_grad=False # Whether or not to track gradients with this tensors operations
                               )
float_32_tensor

tensor([3., 6., 9.])

In [94]:
float_32_tensor.dtype

torch.float32

In [95]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [96]:
float_16_tensor.dtype

torch.float16

In [97]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [98]:
int_64_tensor = torch.tensor([3,6,9],dtype=torch.long)
int_64_tensor

tensor([3, 6, 9])

In [99]:
float_32_tensor * int_64_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [100]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6779, 0.4972, 0.2330, 0.2724],
        [0.3144, 0.6056, 0.5921, 0.5759],
        [0.6136, 0.0230, 0.2131, 0.4572]])

In [101]:
some_tensor.size(), some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [102]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device tensor is on : {some_tensor.device}")

tensor([[0.6779, 0.4972, 0.2330, 0.2724],
        [0.3144, 0.6056, 0.5921, 0.5759],
        [0.6136, 0.0230, 0.2131, 0.4572]])
Datatype of tensor: torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


### Manipulating Tensors (tensor operations)

Tensor operatins include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [103]:
### Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [104]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [105]:
# Subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [106]:
# Try out PyTorch in-builtin functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [107]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the outer dimensions:
* `` (2, 3) * (3, 2) -> (2, 2) ``
* `` (3, 2) * (2, 3) -> (3, 3) ``


In [108]:
torch.matmul(torch.rand(10,10),torch.rand(10,10)).shape

torch.Size([10, 10])

In [109]:
# Element wise multiplication
print(tensor, "*",tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [110]:
# Matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [111]:
tensor @ tensor

tensor(14)

In [112]:
# Matrix multiplication
1 * 1 + 2 * 2  + 3 * 3

14

In [113]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.15 ms, sys: 13 µs, total: 1.16 ms
Wall time: 1.22 ms


In [114]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 246 µs, sys: 30 µs, total: 276 µs
Wall time: 248 µs


tensor(14)

##### One of the most common errors in deep learning : shape errors

In [115]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],[3,4],[5,6]])

tensor_B = torch.tensor([[7,10],[8,11],[9,12]])

torch.matmul(tensor_A,tensor_B.T) # torch.mm is the same as torch.matmul (it's an alias for matmul)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [116]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix out tensor shape issues, we can manipulate the spae of one of our tensor using a **transpose**

A transpose switches the axes or dimensions of a given tensor

In [117]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [118]:
tensor_B.T, tensor_B.T.shape


(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [119]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [120]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes : tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.shape} <- inner dimensions must match")
print("Output : \n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\n Output shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes : tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) <- inner dimensions must match
Output : 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

 Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [121]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [122]:
# Find the min
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [123]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [124]:
# Find the mean - note : the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [125]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [126]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [127]:
# Find the position in tensor that has the minimum value with argmin() -> return index position of target tensor  where the minimum value occurs
x.argmin()

tensor(0)

In [128]:
x[0]

tensor(0)

In [129]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [130]:
x[9]

tensor(90)

In [131]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each oher (v stack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [132]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [133]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [134]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [135]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [136]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [137]:
# torch.squee() - removes all singled dimensions from a target tensor
print( f" Previous tensor : {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimesions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor : {x_squeezed}")
print(f"New shape : {x_squeezed.shape}")

 Previous tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape : torch.Size([9])


In [138]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target : {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\n New tensor: {x_unsqueezed}")
print(f"New shape :{x_unsqueezed.shape}")

Previous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

 New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape :torch.Size([9, 1])


In [139]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1 , 1 -> 2 , 2-> 0

print(f"Previous shape : {x_original.shape}")
print(f"New shape : {x_permuted.shape}")

Previous shape : torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


In [140]:
x_original

tensor([[[0.4158, 0.4472, 0.8977],
         [0.4603, 0.3530, 0.4627],
         [0.1473, 0.2702, 0.2091],
         ...,
         [0.6547, 0.1346, 0.1316],
         [0.6635, 0.3456, 0.3954],
         [0.8619, 0.0655, 0.9563]],

        [[0.4969, 0.9061, 0.8374],
         [0.6671, 0.9699, 0.8615],
         [0.2317, 0.6524, 0.2674],
         ...,
         [0.7402, 0.6974, 0.0294],
         [0.5696, 0.7148, 0.3683],
         [0.5877, 0.5793, 0.9183]],

        [[0.8689, 0.5852, 0.0442],
         [0.5885, 0.3279, 0.8589],
         [0.5117, 0.1544, 0.7538],
         ...,
         [0.7724, 0.2487, 0.2280],
         [0.7738, 0.3991, 0.8388],
         [0.4023, 0.6961, 0.0060]],

        ...,

        [[0.0437, 0.6795, 0.3556],
         [0.2559, 0.3153, 0.8637],
         [0.2955, 0.2320, 0.6157],
         ...,
         [0.4593, 0.2972, 0.8131],
         [0.4337, 0.1292, 0.5622],
         [0.5557, 0.2425, 0.9029]],

        [[0.9532, 0.3465, 0.6423],
         [0.9051, 0.5619, 0.0194],
         [0.

In [141]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [142]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [143]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [144]:
# Let's index on the middle bracket (dim=1)

x[0][0]

tensor([1, 2, 3])

In [145]:
# Let's index on the most inner bracket
x[0][1][1]

tensor(5)

In [146]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [147]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [148]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1,1]

tensor([5])

In [149]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [150]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


### PyTorch tensors & NumPy

Numpy is a popular scientific Python material computing library.

Amd because of this, PyTorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor -> ```torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()


In [151]:
# NumPy array to tensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning : when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [152]:
# Change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [153]:
tensor.dtype

torch.float64

In [154]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [155]:
numpy_tensor.dtype

dtype('float32')

In [156]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducability (trying to take random out of random)

In short how a neural network learns:

``` start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...```

To reduce the randomness in neural networks and PyTorch comes the concept of a random seed

Essentially what the random seed does is "flavour" the randomness

In [157]:
# Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1987, 0.3048, 0.8707, 0.7080],
        [0.3213, 0.3473, 0.9374, 0.2643],
        [0.6328, 0.5655, 0.2067, 0.9752]])
tensor([[0.2441, 0.8789, 0.1839, 0.3058],
        [0.7898, 0.0634, 0.4851, 0.7185],
        [0.5740, 0.4686, 0.7824, 0.2459]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [158]:
# Set the random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


### Extra resources for reproducability


### Running tensors and PyTorch objects on the GPUs (and making faster computations)

1. GPUs = faster computation on numbers, thanks to CUDA + NVDIA hardware + PyTorch working behind the scenes to make everything hunky
2. Use your own GPU - takes a little bit of setup and requires the investment of purchaing a GPUR, there's lot of options
3. Use Cloud computing

In [159]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [160]:
### Check for GPU access with pytorch
import torch
torch.cuda.is_available()

False

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup agnostic code

In [161]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [162]:
# Count number of devices
torch.cuda.device_count()

0

### 3. Putting tensors (and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations

In [163]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [164]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors back to the CPU

In [166]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [167]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPUtensor
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])