<a href="https://colab.research.google.com/github/naveenprasad07/pytorch/blob/main/00_pytorch_fudamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy

In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


### Introduction to Tensors

#### Creating Tensors

In [8]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [10]:
# Get tensor back as Python int
scalar.item()

7

In [12]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX[0]

tensor([7, 8])

In [18]:
MATRIX[1]

tensor([ 9, 10])

In [19]:
MATRIX.shape

torch.Size([2, 2])

In [20]:
# TENSOR
TENSOR =  torch.tensor([[[1,2,3],[3,6,9],[2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [21]:
TENSOR.ndim

3

In [22]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

### Random Tensors

why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

``` Start with random nubmers -> look at data -> update random numbers -> look at data -> update random nubmers```


In [29]:
# Create a random tensor of size (3,4 )
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0157, 0.9974, 0.7422, 0.8870],
        [0.5427, 0.6828, 0.1411, 0.0834],
        [0.1791, 0.1890, 0.4193, 0.0201]])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [26]:
random_tensor.ndim

2

In [34]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3,224,224)) # height,width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeroes and ones

In [38]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [39]:
ones = torch.ones ( size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [40]:
ones.dtype

torch.float32

In [41]:
random_tensor.dtype

torch.float32